development:
  adapter: sqlite3
  database: db/data.sqlite3
  pool: 5
  timeout: 5000

pgdev:
  adapter: postgresql
  encoding: unicode
  database: mail
  pool: 5
  username: mail
  password: phim6rev7fophs4o
